### PR TITLE
ACRS-20: Add production url

### PR DESCRIPTION
**Pull request by gadorcruz**
## What? 
I add the production URL domain name to drone.yml and fix a comment in the file pointing out to the UAT that was the branch environment 
## Why? 
The production URL was pending to be sing off by the stakeholders and the file was created before knowing the domain name. Also, as it is a small changed to familiarize myself with the pull request HO ways of working.
## How? 
By replacing the commented out production name by the actual name
## Testing? 
N/A
## Screenshots (optional) 
N/A
## Anything Else? (optional) 
N/A
## Check list

- [x] I have reviewed my own pull request for linting issues (e.g. adding new lines)
- [ ] I have written tests (if relevant)
- [ ] I have created a JIRA number for my branch
- [ ] I have created a JIRA number for my commit
- [x] I have followed the chris beams method for my commit https://cbea.ms/git-commit/
here is an [example commit](https://github.com/UKHomeOfficeForms/hof/commit/810959f391187c7c4af6db262bcd143b50093a6e)
- [x] Ensure drone builds are green especially tests
- [x] I will squash the commits before merging

### CODE REVIEW

**Comment by gadorcruz** [comment]
Hi Babs, 
As the change is small, I haven't created a Jira ticket as I've told to don't do it. I personally like to create always tickets to link Jira with Github and keep the trail of changes so welcome your opinion with this one please.
Thank you

**Comment by adityababumallisettiHO** [comment]
Great Work @gadorcruz,

We have a Jira ticket for setting up the production environment. We could use this ticket in creating feature branches. And 
https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-20.

**Review by adityababumallisettiHO — APPROVED** [review]
lgtm

**Comment by gadorcruz** [comment]
Thank you, for next time I will add the ticket number to the commits and branch.

**Review by DivineTaminangHO — APPROVED** [review]

**Pull request merged**
